# Generated by Django 5.0.1 on 2024-02-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="profilepic",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="textpost",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
