# Generated by Django 5.0.1 on 2024-02-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual", "0003_blogpost_researchpost_delete_imagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profilepic",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchpost",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
