# Generated by Django 5.0.1 on 2024-02-05 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("virtual", "0006_alter_blogpost_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilepic",
            old_name="image",
            new_name="image_data",
        ),
    ]
